import '../models/genre.dart';

final List<Genre> originalGenres = [
  Genre("JavaScript", "https://storage.googleapis.com/zenn-topics/javascript.png", "javascript"),
  Genre("Python", "https://storage.googleapis.com/zenn-topics/python.png", "python"),
  Genre("TypeScript", "https://storage.googleapis.com/zenn-topics/typescript.png", "typescript"),
  Genre("React", "https://storage.googleapis.com/zenn-topics/react.png", "react"),
  Genre("AWS", "https://storage.googleapis.com/zenn-topics/aws.png", "aws"),
  Genre("Go", "https://storage.googleapis.com/zenn-topics/go.png", "go"),
  Genre("Flutter", "https://storage.googleapis.com/zenn-topics/flutter.png", "flutter"),
  Genre("Docker", "https://storage.googleapis.com/zenn-topics/docker.png", "docker"),
  Genre("iOS", "https://storage.googleapis.com/zenn-topics/ios.png", "ios"),
  Genre("GitHub", "https://storage.googleapis.com/zenn-topics/github.png", "github"),
  Genre("Rails", "https://storage.googleapis.com/zenn-topics/rails.png", "rails"),
  Genre("Ruby", "https://storage.googleapis.com/zenn-topics/ruby.png", "ruby"),
  Genre("Swift", "https://storage.googleapis.com/zenn-topics/swift.png", "swift"),
  Genre("Android", "https://storage.googleapis.com/zenn-topics/android.png", "android"),
  Genre("Next.js", "https://storage.googleapis.com/zenn-topics/nextjs.png", "nextjs"),
  Genre("PHP", "https://storage.googleapis.com/zenn-topics/php.png", "php"),
  Genre("Node.js", "https://storage.googleapis.com/zenn-topics/nodejs.png", "nodejs"),
  Genre("Firebase", "https://storage.googleapis.com/zenn-topics/firebase.png", "firebase"),
  Genre("CSS", "https://storage.googleapis.com/zenn-topics/css.png", "css"),
  Genre("Linux", "https://storage.googleapis.com/zenn-topics/linux.png", "linux"),
  Genre("Git", "https://storage.googleapis.com/zenn-topics/git.png", "git"),
  Genre("ポエム", "https://storage.googleapis.com/zenn-user-upload/topics/29ec1b2192.jpeg", "%E3%83%9D%E3%82%A8%E3%83%A0"),
  Genre("Unity", "https://storage.googleapis.com/zenn-topics/unity.png", "unity"),
  Genre("Vue.js", "https://storage.googleapis.com/zenn-topics/vue.png", "vue"),
  Genre("Web", "https://storage.googleapis.com/zenn-user-upload/topics/bb6b2477a6.jpeg", "web"),
  Genre("Rust", "https://storage.googleapis.com/zenn-topics/rust.png", "rust"),
  Genre("Java", "https://storage.googleapis.com/zenn-topics/java.png", "java"),
  Genre("Mac", "https://storage.googleapis.com/zenn-user-upload/topics/f819ed214b.jpeg", "mac"),
  Genre("Laravel", "https://storage.googleapis.com/zenn-topics/laravel.png", "laravel"),
  Genre("VS Code", "https://storage.googleapis.com/zenn-user-upload/topics/ba102e1425.jpeg", "vscode"),
  Genre("Dart", "https://storage.googleapis.com/zenn-user-upload/topics/d623523c56.jpeg", "dart"),
  Genre("HTML5", "https://storage.googleapis.com/zenn-topics/html.png", "html"),
  Genre("機械学習", "https://storage.googleapis.com/zenn-topics/deep-learning.png", "%E6%A9%9F%E6%A2%B0%E5%AD%A6%E7%BF%92"),
  Genre("Windows", "https://storage.googleapis.com/zenn-user-upload/topics/76fb03b5cf.jpeg", "windows"),
  Genre("GCP", "https://storage.googleapis.com/zenn-topics/gcp.png", "gcp"),
  Genre("C++", "https://storage.googleapis.com/zenn-topics/cplpl.png", "cpp"),
  Genre("Kubernetes", "https://storage.googleapis.com/zenn-topics/kubernetes.png", "kubernetes"),
  Genre("C#", "https://storage.googleapis.com/zenn-topics/csharp.png", "csharp"),
  Genre("GitHub Actions", "https://storage.googleapis.com/zenn-user-upload/topics/da1b8cf8f6.jpeg", "githubactions"),
  Genre("AtCoder", "https://storage.googleapis.com/zenn-user-upload/topics/b88e6a8ea6.png", "atcoder"),
  Genre("Vim", "https://storage.googleapis.com/zenn-topics/vim.png", "vim"),
  Genre("競プロ", "https://zenn.dev/images/topic.png", "%E7%AB%B6%E3%83%97%E3%83%AD"),
  Genre("Test", "https://storage.googleapis.com/zenn-user-upload/topics/902109da93.jpeg", "test"),
  Genre("Kotlin", "https://storage.googleapis.com/zenn-topics/kotlin.png", "kotlin"),
  Genre("MySQL", "https://storage.googleapis.com/zenn-topics/mysql.png", "mysql"),
  Genre("Xcode", "https://storage.googleapis.com/zenn-user-upload/topics/f867f3deb7.jpeg", "xcode"),
  Genre("Ubuntu", "https://storage.googleapis.com/zenn-topics/ubuntu.png", "ubuntu"),
  Genre("Nuxt.js", "https://storage.googleapis.com/zenn-user-upload/topics/3657ecbd05.jpeg", "nuxtjs"),
  Genre("Azure", "https://storage.googleapis.com/zenn-topics/microsoftazure.png", "azure"),
  Genre("プログラミング", "https://storage.googleapis.com/zenn-user-upload/topics/406ad97a28.jpeg", "%E3%83%97%E3%83%AD%E3%82%B0%E3%83%A9%E3%83%9F%E3%83%B3%E3%82%B0"),
  Genre("React Native", "https://storage.googleapis.com/zenn-topics/react.png", "reactnative"),
  Genre("競技プログラミング", "https://zenn.dev/images/topic.png", "%E7%AB%B6%E6%8A%80%E3%83%97%E3%83%AD%E3%82%B0%E3%83%A9%E3%83%9F%E3%83%B3%E3%82%B0"),
  Genre("Terraform", "https://storage.googleapis.com/zenn-user-upload/topics/056b318177.jpeg", "terraform"),
  Genre("API", "https://storage.googleapis.com/zenn-user-upload/topics/204f07b4d5.png", "api"),
  Genre("Slack", "https://storage.googleapis.com/zenn-topics/slack.png", "slack"),
  Genre("frontend", "https://storage.googleapis.com/zenn-user-upload/topics/d766db09a2.jpeg", "frontend"),
  Genre("Firestore", "https://storage.googleapis.com/zenn-topics/firebase.png", "firestore"),
  Genre("Markdown", "https://storage.googleapis.com/zenn-user-upload/topics/86494fe87d.jpeg", "markdown"),
  Genre("Lambda", "https://storage.googleapis.com/zenn-topics/lambda.jpeg", "lambda"),
  Genre("個人開発", "https://storage.googleapis.com/zenn-user-upload/topics/604d5b83b5.jpeg", "%E5%80%8B%E4%BA%BA%E9%96%8B%E7%99%BA")
];
